# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robert Casey Lafferty Website
email: Robert Casey Lafferty <rclafferty@huskers.unl.edu>
description: >- # this means to ignore newlines until "baseurl:"
  I am a third year master's student at the University of Nebraska-Lincoln studying Computer Science. I also have a Bachelor's of Science in Computer Science from Kansas State University, where I focused my studies on cyber security and video game development. I am currently the president of the UNL Game Development Club and studying educational game development/gamification as my master's thesis under Dr. Stephen Cooper.
  
interests: >-
  My interests include software development, game development, cyber security, artificial intelligence, web development, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "rclafferty.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rclafferty1994
github_username:  rclafferty
linkedin_username: rclafferty

# Custom variables
menu_text_index: Home
menu_text_programming: Programming
menu_text_websites: Websites
menu_text_about: About

menu_permalink_index: "/index"
menu_permalink_programming: "/programming"
menu_permalink_websites: "/websites"
menu_permalink_about: "/about"

ksu_homepage_url: https://people.cs.ksu.edu/~rclafferty/

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "subpages"
      # "" means apply to all files
      # "folder_name" means apply to all files within folder_name/
      type: "pages"
    values:
      layout: "page"
      author: "Robert Casey Lafferty"
      img_dir: /static/images/programming/
  -
    scope:
      path: "projects/video_games"
      type: "pages"
    values:
      layout: video_game
      author: "Robert Casey Lafferty"
      language: C#
      platform: Windows
      admin_privileges: None
      is_active: 'No'
      extra_notes: ''
      img_dir: /static/images/programming/
      project_dir: /programming/
  -
    scope:
      path: "projects/software"
      type: "pages"
    values:
      layout: project
      author: "Robert Casey Lafferty"
      language: C#
      platform: Windows
      admin_privileges: None
      is_active: 'No'
      extra_notes: ''
      img_dir: /static/images/programming/
      project_dir: /programming/
  -
    scope:
      path: "projects/websites"
      type: "pages"
    values:
      layout: project
      author: "Robert Casey Lafferty"
      language: C#
      platform: Windows
      admin_privileges: None
      is_active: 'No'
      extra_notes: ''
      img_dir: /static/images/websites/
      project_dir: /websites/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
